version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./master-data:/var/lib/mysql
      - ./master-conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password

  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./slave1-data:/var/lib/mysql
      - ./slave1-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master
    command: --default-authentication-plugin=mysql_native_password

  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slave-2
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    volumes:
      - ./slave2-data:/var/lib/mysql
      - ./slave2-conf:/etc/mysql/conf.d
    depends_on:
      - mysql-master
    command: --default-authentication-plugin=mysql_native_password
